version: '3'

services:
  app:
    container_name: app
    image: app
    build: ./server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./dist:/app/dist
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    restart: always
    volumes:
      - ./dist:/app/dist
    ports:
      - 80:80
    depends_on:
      - app
      - db

  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./duty-bcup-21-02-23.sql:/backup/db.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=duty
